version: "3.11"

services:

  app:
    build:
     context: ./app
    container_name: "FastAPIapp"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/blog/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: "PostgreSQLdb"
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./storage/postgres-data:/var/lib/postgres/data
    restart: always
