version: "3.11"

services:

  app:
    container_name: fastapp
    build:
     context: ./app
    ports:
      - "8000:8000"
    env_file: ./app/.env
    volumes:
      - ./app:/blog/app
    depends_on:
      - db
    restart: always
    
  db:
    container_name: postgre
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./app/.env
    volumes:
      - ./storage/postgres-data:/var/lib/postgres/data
    restart: always

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
