on:
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Build Docker Image
      run: cd app && docker build -t eugenestudio/blog:latest .

    # - name: Run tests
    #   run: |
    #     docker network create mynetwork && \
    #     docker run --network mynetwork -d -p 5000:5000 --name app eugenestudio/blog:latest && \
    #     docker run --network mynetwork eugenestudio/blog:latest pytest

    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && \
        echo "The logining has done successful"

    - name: Push Docker Image to Docker Hub
      run: docker push eugenestudio/blog:latest
  
  prepare-env:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Go to the correct folder
        # run: cd /home/eugene/apps/eugene_studio/
      - name: Create env
        run: cp /home/eugene/apps/eugene_studio/app/.env-example /home/eugene/apps/eugene_studio/app/.env 
      - name: Stop and remove containers, networks
        run: echo ${{ secrets.DOCKER_PASSWORD }} | sudo -S docker compose down
      - name: Remove unused data
        run: echo ${{ secrets.DOCKER_PASSWORD }} | sudo -S docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare-env
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      # - name: Go to the correct folder
      #   run: cd /home/eugene/apps/eugene_studio/
      - name: Create env
        run: cp /home/eugene/apps/eugene_studio/app/.env-example ./app/.env
      - name: docker-compose
        run: echo ${{ secrets.DOCKER_PASSWORD }} | sudo -S docker compose up -d